- params:
      git:
          repoName: WebGoat
          branches:
              - main
      scan:
          includeAllVulnerabilities: true
          failOnSecurityIssues: true
          projects:
              - installCommand: mvn clean install
                workingDirs:
                    - .
