name: "Frogbot Scan Pull Request"
on:
    pull_request_target:
        types: [opened, synchronize]
permissions:
    pull-requests: write
    contents: read
jobs:
    scan-pull-request:
        runs-on: ubuntu-latest
        environment: frogbot
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Set up Java
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - uses: jfrog/frogbot@v2
              env:
                  JF_URL: ${{ secrets.JF_URL }}
                  JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
                  JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
